### PR TITLE
added tested multicall.py addresses

### PR DESCRIPTION
**Pull request by 007vasy**
added validated multicall addresses based on [multicall.py tests](https://github.com/007vasy/multicall.py/blob/master/tests/test_multicall_for_all_chains.py)

as gift and tribute to @0xngmi

### CODE REVIEW

**Comment by 0xngmi** [comment]
we need these multicalls to be deployed very early into a blockchain lifecycle since we'll use them for archive queries, is this the case here?

**Comment by 007vasy** [comment]
sorry, I do not even understand your question, could you elaborate?

**Comment by 007vasy** [comment]
how do I check that?
@0xngmi? why is that relevant? why would a new contract not work on older ones?

**Comment by 0xngmi** [comment]
sorry, I meant that, sometimes, in order to get historical TVL of certain projects, we'll replay the scripts we have for them at a different blockheight (so all calls use a different blockheight). If multicall has been deployed yesterday but we use a blockheight that is from 1 week ago, our calls will fail when they shouldn't be. To avoid that, we need to pick contracts that have been deployed very early into a blockchain's life

**Comment by 007vasy** [comment]
do you have at least on test for that so I can expand on it?

**Comment by 0xngmi** [comment]
i was wrong

**Comment by 007vasy** [comment]
I am a coontributoor

**Pull request merged**
