### PR TITLE
add boba_avax and boba_bnb providers

### PR DESCRIPTION
**Pull request by allush**
Hi!

Could you review and merge this pull request that add two new networks: BOBA_BNB and BOBA_AVAX?

These networks are required to build new symbiosis-finance V2 adapter.

Thanks

### CODE REVIEW

**Comment by allush** [comment]
@g1nt0ki could you look at this PR?

**Comment by g1nt0ki** [comment]
@allush thanks for the PR, especially the multicall addresses, I struggle to find them

**Comment by g1nt0ki** [comment]
new sdk version is published now

**Comment by allush** [comment]
> new sdk version is published now

@g1nt0ki thanks a lot!

**Pull request merged**
