### PR TITLE
Added global rpc request rate limiter

### PR DESCRIPTION
**Pull request by g1nt0ki**
I looked a bit into `@supercharge/promise-pool` but noticed that is is for a fixed array. This would work when there is a single multicall, but what happens when there is multiple multicall requests in parallel

Tested with a configuration of max 100 parallel calls, wait time of 50 ms, ran it against pippi finance which had about 3000 calls in queue at one point, with current configuration it ran in 1:45, previously with batching, it was around 3:00

I am also reading env variables, so we can change the config without updating sdk code

One downside is, I intentionally kept the call limit as sum of calls to all chains, this can be changed. 

Also, I have tested it agains 3k calls in queue, but what happens when it goes over 10k, I am not sure, any adapter that I can use to stress test this?

### CODE REVIEW

**Comment by 0xngmi** [comment]
> but what happens when there is multiple multicall requests in parallel

i think it's fine to just only apply restrictions locally since we still have multiple lambdas running in parallel sending requests and there's no easy way to rate limit globally there

**Comment by 0xngmi** [comment]
>  I am not sure, any adapter that I can use to stress test this?
you can test it against the old adapter for pancake swap, that should have >500k since i think it has more than 150k pairs

**Comment by 0xngmi** [comment]
wdyt about setting a limit per chain instead of a global rate-limit?

**Comment by 0xngmi** [comment]
imo looks good for merging, only thing i'd change would be to limit per chain instead

**Comment by 0xngmi** [comment]
also, when we have that, why not remove the batching altogether? It should make things much faster since atm if 2 requests have finished but one is still waiting it will not attempt the new one

**Comment by 0xngmi** [comment]
and one issue that might pop up is that some protocols might starve: right now as there's no global lock if:
- protocol A has 50 calls
- protocol B has 130k calls

both will start at the same time and protocol B might not finish before the lambda times out, but when you add a global lock it could be possible for protocol B to gobble all the calls , making it impossible for A to finish and breaking both adapters

**Comment by g1nt0ki** [comment]
> > but what happens when there is multiple multicall requests in parallel
> 
> i think it's fine to just only apply restrictions locally since we still have multiple lambdas running in parallel sending requests and there's no easy way to rate limit globally there
> 
> edit: i think your solution is better tho

Yeah, bad naming, by global, I had intended common for all chains, not common for all lambdas

**Comment by g1nt0ki** [comment]
> wdyt about setting a limit per chain instead of a global rate-limit?

I was unsure if this was the right approach, so tried to do minimal work, expanded it to per-chain now

**Comment by g1nt0ki** [comment]
> > I am not sure, any adapter that I can use to stress test this?
> 
> you can test it against the old adapter for pancake swap, that should have >500k since i think it has more than 150k pairs

Dear lord, is that file still in main branch, or how far back do I have to go?

**Comment by g1nt0ki** [comment]
> also, when we have that, why not remove the batching altogether? It should make things much faster since atm if 2 requests have finished but one is still waiting it will not attempt the new one

bit confused about this one, you mean the other PR, or somewhere in the current codebase

**Comment by g1nt0ki** [comment]
> and one issue that might pop up is that some protocols might starve: right now as there's no global lock if:
> 
>     * protocol A has 50 calls
> 
>     * protocol B has 130k calls
> 
> 
> both will start at the same time and protocol B might not finish before the lambda times out, but when you add a global lock it could be possible for protocol B to gobble all the calls , making it impossible for A to finish and breaking both adapters

I am not 100% certain how lambda works, I assumed different lambdas do not use the same memory but more like each is its own process/docker container? wrong assumption?

**Comment by 0xngmi** [comment]
> I am not 100% certain how lambda works, I assumed different lambdas do not use the same memory but more like each is its own process/docker container

yes that's right, but each lambda processes a group of adapters (atm 10 per lambda)

**Comment by 0xngmi** [comment]
> Dear lord, is that file still in main branch, or how far back do I have to go?

Just use this one:
```
const {uniTvlExport} = require('../helper/calculateUniTvl.js')

module.exports = {
  bsc:{
    tvl: uniTvlExport("0xca143ce32fe78f1f7019d7d551a6402fc5350c73", "bsc"),
  },
}
```

> bit confused about this one, you mean the other PR, or somewhere in the current codebase

I meant here https://github.com/DefiLlama/defillama-sdk/blob/master/src/abi/index.ts#L102

**Comment by g1nt0ki** [comment]
> > Dear lord, is that file still in main branch, or how far back do I have to go?
> 
> Just use this one:
> 
> ```
> const {uniTvlExport} = require('../helper/calculateUniTvl.js')
> 
> module.exports = {
>   bsc:{
>     tvl: uniTvlExport("0xca143ce32fe78f1f7019d7d551a6402fc5350c73", "bsc"),
>   },
> }
> ```
> 
> > bit confused about this one, you mean the other PR, or somewhere in the current codebase
> 
> I meant here https://github.com/DefiLlama/defillama-sdk/blob/master/src/abi/index.ts#L102

I am bit puzzled by [this line](https://github.com/DefiLlama/defillama-sdk/blob/master/src/abi/index.ts#L92), for some reason, it always waits for this promise to complete before moning to next call, been looking at it for hours but I dont understand why. I replaced it with promise pool with 20 parallel calls, and the time taken to run the Pancake TVL went from 3880 seconds -> 2049 seconds

is this effect only in my machine, can someone verify?

afterParallel
beforeParallel

**Comment by 0xngmi** [comment]
if we do this through promise-pool shouldn't we remove the extra call rate-limit? or am i missing something?

**Comment by 0xngmi** [comment]
#31 31

**Comment by 0xngmi** [comment]
I ran the sdk with this PR merged against the pancakeswap adapter and i'm getting an out of memory error:
```
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...
Multicall failed, defaulting to single transactions...

<--- Last few GCs --->

[22093:0x60f0fa0]   793800 ms: Scavenge (reduce) 2019.4 (2080.5) -> 2018.8 (2080.1) MB, 24.9 / 0.0 ms  (average mu = 0.266, current mu = 0.237) allocation failure 
[22093:0x60f0fa0]   793832 ms: Scavenge (reduce) 2019.4 (2080.7) -> 2019.4 (2080.7) MB, 25.0 / 0.0 ms  (average mu = 0.266, current mu = 0.237) allocation failure 
[22093:0x60f0fa0]   793866 ms: Scavenge (reduce) 2020.4 (2081.6) -> 2020.4 (2081.6) MB, 25.0 / 0.0 ms  (average mu = 0.266, current mu = 0.237) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb00d90 node::Abort() [node]
 2: 0xa1823b node::FatalError(char const*, char const*) [node]
 3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xea6105  [node]
 6: 0xea6be6  [node]
 7: 0xeb4b1e  [node]
 8: 0xeb5560 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xeb84de v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe7990a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x11f2f06 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x15e7819  [node]
Aborted (core dumped)
```

**Pull request merged**
